### ISSUE TITLE
gurobi issue

### ISSUE THREAD

**Issue by git0929** [autonomous-viranjan/Interactive-Motion-Planning#4]
Is this gurobi necessary? Do I have to apply for this gurobi if I want to use your repository.

error: /home/emc2/vb/gurobi10.0.3_linux64/gurobi1003/linux64/include/gurobi_c++.h: 没有那个文件或目录
    7 | #include "/home/emc2/vb/gurobi10.0.3_linux64/gurobi1003/linux64/include/gurobi_c++.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [expt4/CMakeFiles/planner4_LIB.dir/build.make:76：expt4/CMakeFiles/planner4_LIB.dir/src/jointmpc.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1773：expt4/CMakeFiles/planner4_LIB.dir/all] 错误 2
/home/hou/Interactive-Motion-Planning/src/expt5/src/jointmpc.cpp:7:10: fatal error: /home/emc2/vb/gurobi10.0.3_linux64/gurobi1003/linux64/include/gurobi_c++.h: 没有那个文件或目录
    7 | #include "/home/emc2/vb/gurobi10.0.3_linux64/gurobi1003/linux64/include/gurobi_c++.h"

**Comment by autonomous-viranjan** [comment]
Yes, as mentioned in the `Key Dependencies`, Gurobi is necessary. The MPC is solved using Gurobi. Also, you would need to change the path ` /home/emc2/vb/gurobi10.0.3_linux64/gurobi1003/linux64/include/gurobi_c++.h` to where you install Gurobi.
